### ISSUE TITLE
Ajouter la prise en compte des NNP pour les migrants commençant par 5 ou 6

### ISSUE THREAD

**Issue by Linaida** [assurance-maladie-digital/nir-validation#16]
Hello,

J'ai identifié une petite évolution à faire pour les migrants de passage, leur numéro peuvent commencer par **5** ou  **6**

**Migrant de passage (MIG)**

Le matricule de type MIG  est attribué aux migrants de passage. 
Il possède la même structure que le NNP à  l’exception des codes pour le sexe : **S** : code sexe  **5** = masculin,  **6** = féminin

Le numéro de migrant de calage respecte la structure standard : S V CCC NNNNNNNN

    S : Sexe (5 = masculin, 6 = féminin)
    V : Vérification (=1 pour création au  RFI, =2 pour création au moment du calage)        
    CCC : Numéro de caisse
    NNNNNNNN : Numéro d'ordre par caisse
    
   
Sources [ameli-reseau](https://ameli-reseau.ramage/fiche-technique/definition-et-composition-du-nir-0) :    

![image](https://github.com/user-attachments/assets/f3a81e6c-46d3-4562-a15d-458c721f29ee)

Merci beaucoup  :)    
   
Linda

**Comment by roukmoute** [comment]
Ce n'est pas déjà ce qui est effectué ?

https://github.com/assurance-maladie-digital/nir-validation/blob/master/src/Constraints/MigValidator.php#L57

**Comment by Linaida** [comment]
Salut, je n'avais pas vu le MigValidator 🙈  

Du coup oui ça répond tout à fait à ma demande

Désolée pour l'ouverture de l'issue 😅

Merci à toi
