### ISSUE TITLE
Prise en compte des mois de naissance "lunaire" dans NirValidator

### ISSUE THREAD

**Issue by Linaida** [assurance-maladie-digital/nir-validation#20]
Hello,

Je reviens à la charge 😅 

Serait-il possible de modifier le **NirValidator** afin qu'il puisse prendre en compte les mois de naissance entre 20 et 99.

Pour une fois je vais avoir une sources accessible : https://www.insee.fr/fr/information/6665190?sommaire=6665196

![image](https://github.com/user-attachments/assets/e2bb98c7-8739-4e66-8667-161c68801b8e)

Merci d'avance !

Linda

**Comment by TheoG-Tilak** [comment]
https://github.com/ronanguilloux/IsoCodes/blob/master/src/IsoCodes/Insee.php

**Comment by Linaida** [comment]
Hello, 

J'ai sollicité la MOA du SI qui m'a répondu : 

> De manière générale, le NIR est calculé par le système SNGI et dans ces cas de figure, je ne sais pas dire comment la composante « mois » est calculée. 
> J’ai retrouvé les éléments ci-après dans mes archives, mais je n’en retrouve pas la source : 
> Les personnes concernées sont alors immatriculées avec une composante « mois inconnu » différente des valeurs 01 (janvier) à 12 (décembre). 
> Cette valeur est égale à 20 depuis 1988. Auparavant l’INSEE a pu attribuer les valeurs : 20,30,31 à 42, 51 à 62. 
> 
> Dans une version antérieure du guide de l’identification, il est juste précisé : 
> Il me semble qu’on peut retenir qu’aucune règle précise et claire n’est identifiée.


Suite à ça, mon PO m'a dis qu'on pouvait simplifier la règle de validation afin de vérifier que le mois de naissance se situe : 
- Entre 01 et 12
- ou entre 20 et 99

C'est plus difficile de trouver la règle que l'implémenter xD 

Belle journée à toi
