### ISSUE TITLE
Cas particuliers non gérés

### ISSUE THREAD

**Issue by nstCactus** [assurance-maladie-digital/nir-validation#3]
Wikipédia indique que cette position peut aussi avoir les valeurs suivantes : `3`, `4`, `7` ou `8` ([Signification des chiffres du NIR](https://fr.wikipedia.org/wiki/Num%C3%A9ro_de_s%C3%A9curit%C3%A9_sociale_en_France#Signification_des_chiffres_du_NIR)).

https://github.com/assurance-maladie-digital/nir-validation/blob/fdebf2d783f9edfa6392db2d70dd32d6f8d3309a/src/Constraints/NirValidator.php#L68

**Comment by roukmoute** [comment]
Hello !

Je te remercie de ce retour.

D'après ce que dit Wikipédia, `les cas 3, 4, 7 ou 8 sont pour les personnes en cours d'immatriculation en France`, il ne s'agit donc pas de NIR mais d'un [MIG](https://github.com/assurance-maladie-digital/nir-validation/blob/fdebf2d783f9edfa6392db2d70dd32d6f8d3309a/src/Constraints/MigValidator.php#L54) ou d'un [NPP](https://github.com/assurance-maladie-digital/nir-validation/blob/fdebf2d783f9edfa6392db2d70dd32d6f8d3309a/src/Constraints/MigValidator.php#L54).

Nous ne nous sommes pas basés sur ce que dit Wikipédia, mais sur des informations internes au moment de l'écriture de ce code.

**Comment by nstCactus** [comment]
OK, je me coucherais moins bête !

Merci pour les précisions.
