### ISSUE TITLE
Tag a new release with Symfony 6 compat?

### ISSUE THREAD

**Issue by damienalexandre** [assurance-maladie-digital/nir-validation#5]
Hi!
Thanks for this project, 

would it be possible to tag a new release since #4 has been merged?

Thanks

**Comment by roukmoute** [comment]
You're absolutely right, thanks!
Here's the new version: https://github.com/assurance-maladie-digital/nir-validation/releases/tag/v1.1.0

**Comment by damienalexandre** [comment]
Thank you!
