### ISSUE TITLE
NnpValidator : Prise en compte des nir avec leur matricule (15 caractères)

### ISSUE THREAD

**Issue by Linaida** [assurance-maladie-digital/nir-validation#8]
Hello,

En testant le NnpValidator je me suis rendue compte qu'il ne validait pas les matricules sur 15 caractères comme le fait le NirValidator.

https://github.com/assurance-maladie-digital/nir-validation/blob/ca700cff9a83b2f94cead93f3238624d3c0873f6/src/Constraints/NirValidator.php#L29

https://github.com/assurance-maladie-digital/nir-validation/blob/ca700cff9a83b2f94cead93f3238624d3c0873f6/src/Constraints/NnpValidator.php#L28

Serait-il possible de faire comme pour le NirValidator ?   
   
Merci,    
Linda

**Comment by roukmoute** [comment]
Bonjour @Linaida ,

Merci pour ton message. Après vérification, il semble en effet que le NNP ne prenne pas en compte les 15 caractères, comme indiqué ici : [https://www.aide-sociale.fr/numero-securite-sociale-provisoire/](https://www.aide-sociale.fr/numero-securite-sociale-provisoire/). 

Aurais-tu, par hasard, des informations supplémentaires qui pourraient nous permettre d'ajouter cette règle, si nécessaire ?

Merci d'avance pour ton retour et ton aide !

(Désolé pour le temps de réponse)

**Comment by Linaida** [comment]
Hello @roukmoute ,

J'ai trouvé une documentation métier pour expliquer les différentes structures mais effectivement pour les NNP il n'est pas stipulé qu'on ait à calculer la clé.

Par contre j'ai identifié une petite évolution à faire pour les migrants de passage, leur numéro peuvent commencer par **5** ou  **6**

Ci-dessous les infos que j'ai réussi à récolter :

**Demandeurs` d'asile (type d'accord EXC)**

 Le NNP possède la structure suivante : S V CCC NNNNNNNN

    S : Sexe (7 = masculin, 8 = féminin)
    V : Vérification (= 1 pour le RFI / = 2 pour le calage)        
    CCC : Numéro de caisse
    NNNNNNNN : Numéro d'ordre par caisse

**Migrant de passage (MIG)**

Le matricule de type MIG  est attribué aux migrants de passage. 
Il possède la même structure que le NNP à  l’exception des codes pour le sexe : **S** : code sexe  **5** = masculin,  **6** = féminin

Le numéro de migrant de calage respecte la structure standard : S V CCC NNNNNNNN

    S : Sexe (5 = masculin, 6 = féminin)
    V : Vérification (=1 pour création au  RFI, =2 pour création au moment du calage)        
    CCC : Numéro de caisse
    NNNNNNNN : Numéro d'ordre par caisse
    
   
Sources [ameli-reseau](https://ameli-reseau.ramage/fiche-technique/definition-et-composition-du-nir-0) :    

![image](https://github.com/user-attachments/assets/98e95845-ec60-4268-bade-1bb8d0751e6c)
![image](https://github.com/user-attachments/assets/f3a81e6c-46d3-4562-a15d-458c721f29ee)


Merci beaucoup  :)    
   
Linda
